version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://finanzas2025:finanzas2025@172.30.169.240:5432/polygono

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: finanzas2025
      POSTGRES_PASSWORD: finanzas2025
      POSTGRES_DB: polygono
    ports:
      - "5432:5432"

volumes:
  pg_data:
